spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/TedWithAHammer/sc-config-center
          search-paths: config-client
server:
  port: 50001
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10001/eureka/